package com.lenovo.compass.compass.bean.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ksyun.android.ddlive.bean.business.UserInfo;
import com.ksyun.android.ddlive.bean.business.PushMsgConfig;
import com.ksyun.android.ddlive.bean.business.GiftItem;
import com.ksyun.android.ddlive.bean.business.RemindMsg;
import com.ksyun.android.ddlive.bean.business.ChatRoomRuleMsg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig pushMsgConfigDaoConfig;
    private final DaoConfig giftItemDaoConfig;
    private final DaoConfig remindMsgDaoConfig;
    private final DaoConfig chatRoomRuleMsgDaoConfig;

    private final UserInfoDao userInfoDao;
    private final PushMsgConfigDao pushMsgConfigDao;
    private final GiftItemDao giftItemDao;
    private final RemindMsgDao remindMsgDao;
    private final ChatRoomRuleMsgDao chatRoomRuleMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        pushMsgConfigDaoConfig = daoConfigMap.get(PushMsgConfigDao.class).clone();
        pushMsgConfigDaoConfig.initIdentityScope(type);

        giftItemDaoConfig = daoConfigMap.get(GiftItemDao.class).clone();
        giftItemDaoConfig.initIdentityScope(type);

        remindMsgDaoConfig = daoConfigMap.get(RemindMsgDao.class).clone();
        remindMsgDaoConfig.initIdentityScope(type);

        chatRoomRuleMsgDaoConfig = daoConfigMap.get(ChatRoomRuleMsgDao.class).clone();
        chatRoomRuleMsgDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        pushMsgConfigDao = new PushMsgConfigDao(pushMsgConfigDaoConfig, this);
        giftItemDao = new GiftItemDao(giftItemDaoConfig, this);
        remindMsgDao = new RemindMsgDao(remindMsgDaoConfig, this);
        chatRoomRuleMsgDao = new ChatRoomRuleMsgDao(chatRoomRuleMsgDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(PushMsgConfig.class, pushMsgConfigDao);
        registerDao(GiftItem.class, giftItemDao);
        registerDao(RemindMsg.class, remindMsgDao);
        registerDao(ChatRoomRuleMsg.class, chatRoomRuleMsgDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        pushMsgConfigDaoConfig.getIdentityScope().clear();
        giftItemDaoConfig.getIdentityScope().clear();
        remindMsgDaoConfig.getIdentityScope().clear();
        chatRoomRuleMsgDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public PushMsgConfigDao getPushMsgConfigDao() {
        return pushMsgConfigDao;
    }

    public GiftItemDao getGiftItemDao() {
        return giftItemDao;
    }

    public RemindMsgDao getRemindMsgDao() {
        return remindMsgDao;
    }

    public ChatRoomRuleMsgDao getChatRoomRuleMsgDao() {
        return chatRoomRuleMsgDao;
    }

}
