package com.lenovo.compass.compass.bean.business;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "user".
 */
public class UserInfo implements Parcelable {

    private Long id;
    private int userId;
    /**
     * Not-null value.
     */
    private String userName = "";
    /**
     * Not-null value.
     */
    private String avatarUrl = "";
    private int userSex = 3;
    private boolean isAnchor;
    private int anchorRoomId;
    private int yunpiaoNum;
    private int concernNum;
    private int concernedNum;
    private int historyPlayNum;
    private int userPos;
    /**
     * Not-null value.
     */
    private String userAbstract = "";
    private int level;
    private int userMoney;
    /**
     * Not-null value.
     */
    private String userThumbnail = "";
    private int userDiamond;
    private int userCharm;
    private int userExperience;
    private int userInvest;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, int userId, String userName, String avatarUrl, int userSex, boolean isAnchor, int anchorRoomId, int yunpiaoNum, int concernNum, int concernedNum, int historyPlayNum, int userPos, String userAbstract, int level, int userMoney, String userThumbnail, int userDiamond, int userCharm, int userExperience, int userInvest) {
        this.id = id;
        this.userId = userId;
        this.userName = userName;
        this.avatarUrl = avatarUrl;
        this.userSex = userSex;
        this.isAnchor = isAnchor;
        this.anchorRoomId = anchorRoomId;
        this.yunpiaoNum = yunpiaoNum;
        this.concernNum = concernNum;
        this.concernedNum = concernedNum;
        this.historyPlayNum = historyPlayNum;
        this.userPos = userPos;
        this.userAbstract = userAbstract;
        this.level = level;
        this.userMoney = userMoney;
        this.userThumbnail = userThumbnail;
        this.userDiamond = userDiamond;
        this.userCharm = userCharm;
        this.userExperience = userExperience;
        this.userInvest = userInvest;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * Not-null value.
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Not-null value.
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public int getUserSex() {
        return userSex;
    }

    public void setUserSex(int userSex) {
        this.userSex = userSex;
    }

    public boolean getIsAnchor() {
        return isAnchor;
    }

    public void setIsAnchor(boolean isAnchor) {
        this.isAnchor = isAnchor;
    }

    public int getAnchorRoomId() {
        return anchorRoomId;
    }

    public void setAnchorRoomId(int anchorRoomId) {
        this.anchorRoomId = anchorRoomId;
    }

    public int getYunpiaoNum() {
        return yunpiaoNum;
    }

    public void setYunpiaoNum(int yunpiaoNum) {
        this.yunpiaoNum = yunpiaoNum;
    }

    public int getConcernNum() {
        return concernNum;
    }

    public void setConcernNum(int concernNum) {
        this.concernNum = concernNum;
    }

    public int getConcernedNum() {
        return concernedNum;
    }

    public void setConcernedNum(int concernedNum) {
        this.concernedNum = concernedNum;
    }

    public int getHistoryPlayNum() {
        return historyPlayNum;
    }

    public void setHistoryPlayNum(int historyPlayNum) {
        this.historyPlayNum = historyPlayNum;
    }

    public int getUserPos() {
        return userPos;
    }

    public void setUserPos(int userPos) {
        this.userPos = userPos;
    }

    /**
     * Not-null value.
     */
    public String getUserAbstract() {
        return userAbstract;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserAbstract(String userAbstract) {
        this.userAbstract = userAbstract;
    }

    public int getLevel() {
        if (level < 1) {
            return 1;
        }
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public int getUserMoney() {
        return userMoney;
    }

    public void setUserMoney(int userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * Not-null value.
     */
    public String getUserThumbnail() {
        return userThumbnail;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserThumbnail(String userThumbnail) {
        this.userThumbnail = userThumbnail;
    }

    public int getUserDiamond() {
        return userDiamond;
    }

    public void setUserDiamond(int userDiamond) {
        this.userDiamond = userDiamond;
    }

    public int getUserCharm() {
        return userCharm;
    }

    public void setUserCharm(int userCharm) {
        this.userCharm = userCharm;
    }

    public int getUserExperience() {
        return userExperience;
    }

    public void setUserExperience(int userExperience) {
        this.userExperience = userExperience;
    }

    public int getUserInvest() {
        return userInvest;
    }

    public void setUserInvest(int userInvest) {
        this.userInvest = userInvest;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeInt(this.userId);
        dest.writeString(this.userName);
        dest.writeString(this.avatarUrl);
        dest.writeInt(this.userSex);
        dest.writeByte(this.isAnchor ? (byte) 1 : (byte) 0);
        dest.writeInt(this.anchorRoomId);
        dest.writeInt(this.yunpiaoNum);
        dest.writeInt(this.concernNum);
        dest.writeInt(this.concernedNum);
        dest.writeInt(this.historyPlayNum);
        dest.writeInt(this.userPos);
        dest.writeString(this.userAbstract);
        dest.writeInt(this.level);
        dest.writeInt(this.userMoney);
        dest.writeString(this.userThumbnail);
        dest.writeInt(this.userDiamond);
        dest.writeInt(this.userCharm);
        dest.writeInt(this.userExperience);
        dest.writeInt(this.userInvest);
    }

    protected UserInfo(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.userId = in.readInt();
        this.userName = in.readString();
        this.avatarUrl = in.readString();
        this.userSex = in.readInt();
        this.isAnchor = in.readByte() != 0;
        this.anchorRoomId = in.readInt();
        this.yunpiaoNum = in.readInt();
        this.concernNum = in.readInt();
        this.concernedNum = in.readInt();
        this.historyPlayNum = in.readInt();
        this.userPos = in.readInt();
        this.userAbstract = in.readString();
        this.level = in.readInt();
        this.userMoney = in.readInt();
        this.userThumbnail = in.readString();
        this.userDiamond = in.readInt();
        this.userCharm = in.readInt();
        this.userExperience = in.readInt();
        this.userInvest = in.readInt();
    }

    public static final Creator<UserInfo> CREATOR = new Creator<UserInfo>() {
        @Override
        public UserInfo createFromParcel(Parcel source) {
            return new UserInfo(source);
        }

        @Override
        public UserInfo[] newArray(int size) {
            return new UserInfo[size];
        }
    };
}
